sudo: required

language: go

go:
  - 1.8
  - 1.8.x
  - 1.9
  - 1.9.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls

script:
  - glide install
  - go test $(glide nv)

after_success:
  # the main.go file is fully covered in main_test.go
  - goveralls -service=travis-ci -ignore="main.go"
